name = "M_OS"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true
